######################################################################
# Automatically generated by qmake (3.0) Sat Dec 3 00:00:20 2016
######################################################################

TEMPLATE = app
TARGET = shared_ptr_get_reference
INCLUDEPATH += .
CONFIG += c++11

# Input
SOURCES += main.cpp
