######################################################################
# Automatically generated by qmake (3.0) Fri Dec 2 17:27:16 2016
######################################################################

TEMPLATE = app
TARGET = sending_signal_without_eventloop_in_thread
INCLUDEPATH += .

# Input
SOURCES += main.cpp
