######################################################################
# Automatically generated by qmake (3.0) Sat Dec 3 20:47:38 2016
######################################################################

TEMPLATE = app
TARGET = virtual_destructor
INCLUDEPATH += .

# Input
SOURCES += main.cpp
